### ISSUE TITLE
App gallery crashing when you click edit.

### ISSUE THREAD

**Issue by DienoX** [Tkkg1994/NovaRom#1]
Dc only is on this now rom (problem is gallery from s6?).
http://i.imgur.com/ydbdFnx.jpg
This issue tested on fresh NovaRom.

**Comment by Tkkg1994** [comment]
With video or photograph?

**Comment by DienoX** [comment]
Look.  https://youtu.be/WatrQuU3LUg

**Comment by DienoX** [comment]
@photograph

**Comment by Tkkg1994** [comment]
https://github.com/Tkkg1994/NovaRom/commit/a733875e7623f6efd44b6271dc9ce523ce096cbb

**Comment by DienoX** [comment]
Thanks for fix it.
